name: "Build n Publish Hunts"
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 10 * * *'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: tsitu/mhct-db-docker

      # https://github.com/orgs/community/discussions/26351
      - name: Free up some disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: tsitu/mhct-db-docker:nightly,tsitu/mhct-db-docker:latest
          labels: ${{ steps.meta.outputs.labels }}

      # Action to keep workflow going before 60 days of repo inactivity
      - uses: gautamkrishnar/keepalive-workflow@v1
