name: "Build n Publish MapSpotter"
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 13 * * 3'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: tsitu/mhct-db-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: DockerfileMaps
          push: true
          tags: tsitu/mhct-db-docker:mapspotter
          labels: ${{ steps.meta.outputs.labels }}
